/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.controllers;

import com.shell.apitest.ApiHelper;
import com.shell.apitest.Server;
import com.shell.apitest.exceptions.ApiException;
import com.shell.apitest.exceptions.TransactionDataV1Cardusagesummary400ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Cardusagesummary401ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Cardusagesummary403ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Cardusagesummary404ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Cardusagesummary500ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Exceptions400ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Exceptions401ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Exceptions403ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Exceptions404ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Exceptions500ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Fees400ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Fees401ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Fees403ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Fees404ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Fees500ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Feessummary400ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Feessummary401ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Feessummary403ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Feessummary404ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Feessummary500ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Fuelconsumption400ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Fuelconsumption401ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Fuelconsumption403ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Fuelconsumption404ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Fuelconsumption500ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Multipayerspricedtransactions400ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Multipayerspricedtransactions401ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Multipayerspricedtransactions403ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Multipayerspricedtransactions404ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Multipayerspricedtransactions500ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Priced400ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Priced401ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Priced403ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Priced404ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Priced500ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Pricedtransaction400ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Pricedtransaction401ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Pricedtransaction403ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Pricedtransaction404ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Pricedtransaction500ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Pricedtransactionssummary400ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Pricedtransactionssummary401ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Pricedtransactionssummary403ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Pricedtransactionssummary404ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Pricedtransactionssummary500ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Recent400ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Recent401ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Recent403ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Recent404ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Recent500ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Updateodometer400ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Updateodometer401ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Updateodometer403ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Updateodometer404ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Updateodometer500ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Volumebasedbonus400ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Volumebasedbonus401ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Volumebasedbonus403ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Volumebasedbonus404ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Volumebasedbonus500ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Volumebasedpricing400ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Volumebasedpricing401ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Volumebasedpricing403ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Volumebasedpricing404ErrorException;
import com.shell.apitest.exceptions.TransactionDataV1Volumebasedpricing500ErrorException;
import com.shell.apitest.http.request.HttpMethod;
import com.shell.apitest.models.CardUsageSummaryReq;
import com.shell.apitest.models.CardUsageSummaryRes;
import com.shell.apitest.models.FeeSummaryResponse;
import com.shell.apitest.models.FuelConsumptionReq;
import com.shell.apitest.models.FuelConsumptionResponse;
import com.shell.apitest.models.MultiPricedTransactionReq;
import com.shell.apitest.models.MultiPricedTransactionRes;
import com.shell.apitest.models.PriceTransSummaryReq;
import com.shell.apitest.models.PriceTransactionReq;
import com.shell.apitest.models.PricedTransSummaryResp;
import com.shell.apitest.models.PricedTransactionRequestV2;
import com.shell.apitest.models.PricedTransactionRes;
import com.shell.apitest.models.PricedTransactionResponseV2;
import com.shell.apitest.models.RecentTransactionRequest;
import com.shell.apitest.models.RecentTransactionsResponse;
import com.shell.apitest.models.TransactionExceptionsReq;
import com.shell.apitest.models.TransactionExceptionsRes;
import com.shell.apitest.models.TransactionFeesReq;
import com.shell.apitest.models.TransactionFeesRes;
import com.shell.apitest.models.TransactionFeesSummaryReq;
import com.shell.apitest.models.UpdateOdometerRequest;
import com.shell.apitest.models.UpdateOdometerResp;
import com.shell.apitest.models.VolumeBasedBonusReq;
import com.shell.apitest.models.VolumeBasedBonusRes;
import com.shell.apitest.models.VolumeBasedPricingReq;
import com.shell.apitest.models.VolumeBasedPricingRes;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class TransactionController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public TransactionController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * This API allows querying transaction data (i.e. Priced, Billed and Unbilled sales items). It
     * provides a flexible search criteria and supports paging. Transactions that are posted but not
     * yet priced, billed or that are in error will not be returned by this API. The API also
     * supports returning Fee Items. #### Supported operations * Get sales items and fee
     * transactions * Search by invoice status * Search by fixed date period * Search by date range
     * * Search by account * Search by card * Get sales items only * Search by transaction Id or
     * location * Search by transaction posting date * Search by invoice number or date * Search by
     * driver name or vehicle registration number * Search by card group * Search by fuel only
     * transactions * Search by product This API fetches transactions for a period based on the
     * below parameters and priority order: 1. InvoiceNumber 2. InvoiceDate 3. FromDate, ToDate 4.
     * PostingFromDate, PostingToDate (Can be used only when IncludeFees = false) 5.
     * InvoiceDateFrom, InvoiceDateTo 6. Period This API considers only one of the above set of
     * parameters at a time. For example, if InvoiceNumber and Period are provided in the input then
     * Period is ignored and transactions associated to the given invoice number are returned. If
     * none of the above parameters are provided then last 7 days transactions will be fetched. This
     * operation can fetch transactions that are old up to 24 (configurable) months. However, the
     * date range between any of the ‘From’ and ‘To’ dates in the above combination cannot be more
     * than 210 (configurable) days.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: Priced Transaction Request Body
     * @return    Returns the PricedTransactionRes response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public PricedTransactionRes pricedTransactions(
            final String requestId,
            final PriceTransactionReq body) throws ApiException, IOException {
        return preparePricedTransactionsRequest(requestId, body).execute();
    }

    /**
     * This API allows querying transaction data (i.e. Priced, Billed and Unbilled sales items). It
     * provides a flexible search criteria and supports paging. Transactions that are posted but not
     * yet priced, billed or that are in error will not be returned by this API. The API also
     * supports returning Fee Items. #### Supported operations * Get sales items and fee
     * transactions * Search by invoice status * Search by fixed date period * Search by date range
     * * Search by account * Search by card * Get sales items only * Search by transaction Id or
     * location * Search by transaction posting date * Search by invoice number or date * Search by
     * driver name or vehicle registration number * Search by card group * Search by fuel only
     * transactions * Search by product This API fetches transactions for a period based on the
     * below parameters and priority order: 1. InvoiceNumber 2. InvoiceDate 3. FromDate, ToDate 4.
     * PostingFromDate, PostingToDate (Can be used only when IncludeFees = false) 5.
     * InvoiceDateFrom, InvoiceDateTo 6. Period This API considers only one of the above set of
     * parameters at a time. For example, if InvoiceNumber and Period are provided in the input then
     * Period is ignored and transactions associated to the given invoice number are returned. If
     * none of the above parameters are provided then last 7 days transactions will be fetched. This
     * operation can fetch transactions that are old up to 24 (configurable) months. However, the
     * date range between any of the ‘From’ and ‘To’ dates in the above combination cannot be more
     * than 210 (configurable) days.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: Priced Transaction Request Body
     * @return    Returns the PricedTransactionRes response from the API call
     */
    public CompletableFuture<PricedTransactionRes> pricedTransactionsAsync(
            final String requestId,
            final PriceTransactionReq body) {
        try {
            return preparePricedTransactionsRequest(requestId, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for pricedTransactions.
     */
    private ApiCall<PricedTransactionRes, ApiException> preparePricedTransactionsRequest(
            final String requestId,
            final PriceTransactionReq body) {
        return new ApiCall.Builder<PricedTransactionRes, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SHELL.value())
                        .path("/transaction-data/v1/pricedtransaction")
                        .bodyParam(param -> param.value(body).isRequired(false))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("RequestId")
                                .value(requestId).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("BearerToken"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, PricedTransactionRes.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).",
                                (reason, context) -> new TransactionDataV1Pricedtransaction400ErrorException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("The request has not been applied because it lacks valid  authentication credentials for the target resource.",
                                (reason, context) -> new TransactionDataV1Pricedtransaction401ErrorException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new TransactionDataV1Pricedtransaction403ErrorException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.",
                                (reason, context) -> new TransactionDataV1Pricedtransaction404ErrorException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("The server encountered an unexpected condition that  prevented it from fulfilling the request.",
                                (reason, context) -> new TransactionDataV1Pricedtransaction500ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This API returns the transaction summary data (i.e. Priced, Billed and Unbilled sales items).
     * It provides a flexible search criteria. The API also supports returning Fee Items.
     * Transactions posted for fee items that are in error are not included in the summary. The
     * endpoint supports the exact same search criteria as the endpoint
     * *transaction/prciedtransactions*. #### Supported operations * Get sales items and fee
     * transactions * Search by invoice status * Search by fixed date period * Search by date range
     * * Search by account * Search by card * Get sales items only * Search by transaction Id or
     * location * Search by transaction posting date * Search by invoice number or date * Search by
     * driver name or vehicle registration number * Search by card group * Search by fuel only
     * transactions * Search by product This API fetches transactions for a period based on the
     * below parameters and priority order: 1. InvoiceNumber 2. InvoiceDate 3. FromDate, ToDate 4.
     * PostingFromDate, PostingToDate (Can be used only when IncludeFees = false) 5.
     * InvoiceDateFrom, InvoiceDateTo 6. Period This API considers only one of the above set of
     * parameters at a time. For example, if InvoiceNumber and Period are provided in the input then
     * Period is ignored and transactions associated to the given invoice number are returned. If
     * none of the above parameters are provided then last 7 days transactions will be fetched.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: PricedSummary RequestBody
     * @return    Returns the PricedTransSummaryResp response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public PricedTransSummaryResp pricedTransactionsSummary(
            final String requestId,
            final PriceTransSummaryReq body) throws ApiException, IOException {
        return preparePricedTransactionsSummaryRequest(requestId, body).execute();
    }

    /**
     * This API returns the transaction summary data (i.e. Priced, Billed and Unbilled sales items).
     * It provides a flexible search criteria. The API also supports returning Fee Items.
     * Transactions posted for fee items that are in error are not included in the summary. The
     * endpoint supports the exact same search criteria as the endpoint
     * *transaction/prciedtransactions*. #### Supported operations * Get sales items and fee
     * transactions * Search by invoice status * Search by fixed date period * Search by date range
     * * Search by account * Search by card * Get sales items only * Search by transaction Id or
     * location * Search by transaction posting date * Search by invoice number or date * Search by
     * driver name or vehicle registration number * Search by card group * Search by fuel only
     * transactions * Search by product This API fetches transactions for a period based on the
     * below parameters and priority order: 1. InvoiceNumber 2. InvoiceDate 3. FromDate, ToDate 4.
     * PostingFromDate, PostingToDate (Can be used only when IncludeFees = false) 5.
     * InvoiceDateFrom, InvoiceDateTo 6. Period This API considers only one of the above set of
     * parameters at a time. For example, if InvoiceNumber and Period are provided in the input then
     * Period is ignored and transactions associated to the given invoice number are returned. If
     * none of the above parameters are provided then last 7 days transactions will be fetched.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: PricedSummary RequestBody
     * @return    Returns the PricedTransSummaryResp response from the API call
     */
    public CompletableFuture<PricedTransSummaryResp> pricedTransactionsSummaryAsync(
            final String requestId,
            final PriceTransSummaryReq body) {
        try {
            return preparePricedTransactionsSummaryRequest(requestId, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for pricedTransactionsSummary.
     */
    private ApiCall<PricedTransSummaryResp, ApiException> preparePricedTransactionsSummaryRequest(
            final String requestId,
            final PriceTransSummaryReq body) {
        return new ApiCall.Builder<PricedTransSummaryResp, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SHELL.value())
                        .path("/transaction-data/v1/pricedtransactionssummary")
                        .bodyParam(param -> param.value(body).isRequired(false))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("RequestId")
                                .value(requestId).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("BearerToken"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, PricedTransSummaryResp.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).",
                                (reason, context) -> new TransactionDataV1Pricedtransactionssummary400ErrorException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("The request has not been applied because it lacks valid  authentication credentials for the target resource.",
                                (reason, context) -> new TransactionDataV1Pricedtransactionssummary401ErrorException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new TransactionDataV1Pricedtransactionssummary403ErrorException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.",
                                (reason, context) -> new TransactionDataV1Pricedtransactionssummary404ErrorException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("The server encountered an unexpected condition that  prevented it from fulfilling the request.",
                                (reason, context) -> new TransactionDataV1Pricedtransactionssummary500ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This API allows querying transaction data (i.e. Priced, Billed and Unbilled sales items) for
     * multiple payers. It provides a flexible search criteria and supports paging. Transactions
     * that are posted but not yet priced, billed or that are in error will not be returned by this
     * API. The API also supports returning Fee Items. At least one payer should be provided.
     * Multiple payers must belong to the same payer group. #### Supported operations * Get sales
     * items and fee transactions for multiple payers * Search by invoice status * Search by fixed
     * date period * Search by date range * Get sales items only for multiple payers * Search by
     * transaction location * Search by transaction posting date * Search by invoice number or date
     * * Search by fuel only transactions This API fetches transactions for a period based on the
     * below parameters and priority order: 1. InvoiceNumber 2. InvoiceDate 3. FromDate, ToDate 4.
     * PostingFromDate, PostingToDate (Can be used only when IncludeFees = false) 5.
     * InvoiceDateFrom, InvoiceDateTo 6. Period This API considers only one of the above set of
     * parameters at a time. For example, if InvoiceNumber and Period are provided in the input then
     * Period is ignored and transactions associated to the given invoice number are returned. If
     * none of the above parameters are provided then last 7 days transactions will be fetched.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: MultiPayer RequestBody
     * @return    Returns the MultiPricedTransactionRes response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public MultiPricedTransactionRes multipricedTransactions(
            final String requestId,
            final MultiPricedTransactionReq body) throws ApiException, IOException {
        return prepareMultipricedTransactionsRequest(requestId, body).execute();
    }

    /**
     * This API allows querying transaction data (i.e. Priced, Billed and Unbilled sales items) for
     * multiple payers. It provides a flexible search criteria and supports paging. Transactions
     * that are posted but not yet priced, billed or that are in error will not be returned by this
     * API. The API also supports returning Fee Items. At least one payer should be provided.
     * Multiple payers must belong to the same payer group. #### Supported operations * Get sales
     * items and fee transactions for multiple payers * Search by invoice status * Search by fixed
     * date period * Search by date range * Get sales items only for multiple payers * Search by
     * transaction location * Search by transaction posting date * Search by invoice number or date
     * * Search by fuel only transactions This API fetches transactions for a period based on the
     * below parameters and priority order: 1. InvoiceNumber 2. InvoiceDate 3. FromDate, ToDate 4.
     * PostingFromDate, PostingToDate (Can be used only when IncludeFees = false) 5.
     * InvoiceDateFrom, InvoiceDateTo 6. Period This API considers only one of the above set of
     * parameters at a time. For example, if InvoiceNumber and Period are provided in the input then
     * Period is ignored and transactions associated to the given invoice number are returned. If
     * none of the above parameters are provided then last 7 days transactions will be fetched.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: MultiPayer RequestBody
     * @return    Returns the MultiPricedTransactionRes response from the API call
     */
    public CompletableFuture<MultiPricedTransactionRes> multipricedTransactionsAsync(
            final String requestId,
            final MultiPricedTransactionReq body) {
        try {
            return prepareMultipricedTransactionsRequest(requestId, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for multipricedTransactions.
     */
    private ApiCall<MultiPricedTransactionRes, ApiException> prepareMultipricedTransactionsRequest(
            final String requestId,
            final MultiPricedTransactionReq body) {
        return new ApiCall.Builder<MultiPricedTransactionRes, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SHELL.value())
                        .path("/transaction-data/v1/multipayerspricedtransactions")
                        .bodyParam(param -> param.value(body).isRequired(false))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("RequestId")
                                .value(requestId).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("BearerToken"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, MultiPricedTransactionRes.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).",
                                (reason, context) -> new TransactionDataV1Multipayerspricedtransactions400ErrorException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("The request has not been applied because it lacks valid  authentication credentials for the target resource.",
                                (reason, context) -> new TransactionDataV1Multipayerspricedtransactions401ErrorException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new TransactionDataV1Multipayerspricedtransactions403ErrorException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.",
                                (reason, context) -> new TransactionDataV1Multipayerspricedtransactions404ErrorException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("The server encountered an unexpected condition that  prevented it from fulfilling the request.",
                                (reason, context) -> new TransactionDataV1Multipayerspricedtransactions500ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This operation is to provide the expenditure analysis for a card for the past 7 months. The
     * response contains a daily summary of the transactions (billed &amp; unbilled) from 1st of the
     * last 7 months for the requested card grouped by card, site-group and product.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: Card Usage Summary RequestBody
     * @return    Returns the CardUsageSummaryRes response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public CardUsageSummaryRes cardUsageSummary(
            final String requestId,
            final CardUsageSummaryReq body) throws ApiException, IOException {
        return prepareCardUsageSummaryRequest(requestId, body).execute();
    }

    /**
     * This operation is to provide the expenditure analysis for a card for the past 7 months. The
     * response contains a daily summary of the transactions (billed &amp; unbilled) from 1st of the
     * last 7 months for the requested card grouped by card, site-group and product.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: Card Usage Summary RequestBody
     * @return    Returns the CardUsageSummaryRes response from the API call
     */
    public CompletableFuture<CardUsageSummaryRes> cardUsageSummaryAsync(
            final String requestId,
            final CardUsageSummaryReq body) {
        try {
            return prepareCardUsageSummaryRequest(requestId, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for cardUsageSummary.
     */
    private ApiCall<CardUsageSummaryRes, ApiException> prepareCardUsageSummaryRequest(
            final String requestId,
            final CardUsageSummaryReq body) {
        return new ApiCall.Builder<CardUsageSummaryRes, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SHELL.value())
                        .path("/transaction-data/v1/cardusagesummary")
                        .bodyParam(param -> param.value(body).isRequired(false))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("RequestId")
                                .value(requestId).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("BearerToken"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, CardUsageSummaryRes.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).",
                                (reason, context) -> new TransactionDataV1Cardusagesummary400ErrorException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("The request has not been applied because it lacks valid  authentication credentials for the target resource.",
                                (reason, context) -> new TransactionDataV1Cardusagesummary401ErrorException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new TransactionDataV1Cardusagesummary403ErrorException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.",
                                (reason, context) -> new TransactionDataV1Cardusagesummary404ErrorException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("The server encountered an unexpected condition that  prevented it from fulfilling the request.",
                                (reason, context) -> new TransactionDataV1Cardusagesummary500ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * - This API provides the details of the bonus and/or association bonus rules setup for the
     * given payer and that are active on the current date. - This API also returns the details of
     * the monthly breakup of current period consumption as well as the details of the previously
     * calculated bonus and consumption of the applicable payers.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: VolumeBasedBonus RequestBody
     * @return    Returns the VolumeBasedBonusRes response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public VolumeBasedBonusRes volumeBasedBonus(
            final String requestId,
            final VolumeBasedBonusReq body) throws ApiException, IOException {
        return prepareVolumeBasedBonusRequest(requestId, body).execute();
    }

    /**
     * - This API provides the details of the bonus and/or association bonus rules setup for the
     * given payer and that are active on the current date. - This API also returns the details of
     * the monthly breakup of current period consumption as well as the details of the previously
     * calculated bonus and consumption of the applicable payers.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: VolumeBasedBonus RequestBody
     * @return    Returns the VolumeBasedBonusRes response from the API call
     */
    public CompletableFuture<VolumeBasedBonusRes> volumeBasedBonusAsync(
            final String requestId,
            final VolumeBasedBonusReq body) {
        try {
            return prepareVolumeBasedBonusRequest(requestId, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for volumeBasedBonus.
     */
    private ApiCall<VolumeBasedBonusRes, ApiException> prepareVolumeBasedBonusRequest(
            final String requestId,
            final VolumeBasedBonusReq body) {
        return new ApiCall.Builder<VolumeBasedBonusRes, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SHELL.value())
                        .path("/transaction-data/v1/volumebasedbonus")
                        .bodyParam(param -> param.value(body).isRequired(false))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("RequestId")
                                .value(requestId).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("BearerToken"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, VolumeBasedBonusRes.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).",
                                (reason, context) -> new TransactionDataV1Volumebasedbonus400ErrorException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("The request has not been applied because it lacks valid  authentication credentials for the target resource.",
                                (reason, context) -> new TransactionDataV1Volumebasedbonus401ErrorException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new TransactionDataV1Volumebasedbonus403ErrorException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.",
                                (reason, context) -> new TransactionDataV1Volumebasedbonus404ErrorException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("The server encountered an unexpected condition that  prevented it from fulfilling the request.",
                                (reason, context) -> new TransactionDataV1Volumebasedbonus500ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * - This API will return the details of the in arrear fee rule applied to the payer along with
     * details of locations, products, tiers as applied. - It will also show historical and current
     * volume consumption and related tier applied for the following month.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: VolumeBasedPricing RequestBody
     * @return    Returns the VolumeBasedPricingRes response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public VolumeBasedPricingRes volumeBasedPricing(
            final String requestId,
            final VolumeBasedPricingReq body) throws ApiException, IOException {
        return prepareVolumeBasedPricingRequest(requestId, body).execute();
    }

    /**
     * - This API will return the details of the in arrear fee rule applied to the payer along with
     * details of locations, products, tiers as applied. - It will also show historical and current
     * volume consumption and related tier applied for the following month.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: VolumeBasedPricing RequestBody
     * @return    Returns the VolumeBasedPricingRes response from the API call
     */
    public CompletableFuture<VolumeBasedPricingRes> volumeBasedPricingAsync(
            final String requestId,
            final VolumeBasedPricingReq body) {
        try {
            return prepareVolumeBasedPricingRequest(requestId, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for volumeBasedPricing.
     */
    private ApiCall<VolumeBasedPricingRes, ApiException> prepareVolumeBasedPricingRequest(
            final String requestId,
            final VolumeBasedPricingReq body) {
        return new ApiCall.Builder<VolumeBasedPricingRes, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SHELL.value())
                        .path("/transaction-data/v1/volumebasedpricing")
                        .bodyParam(param -> param.value(body).isRequired(false))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("RequestId")
                                .value(requestId).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("BearerToken"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, VolumeBasedPricingRes.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).",
                                (reason, context) -> new TransactionDataV1Volumebasedpricing400ErrorException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("The request has not been applied because it lacks valid  authentication credentials for the target resource.",
                                (reason, context) -> new TransactionDataV1Volumebasedpricing401ErrorException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new TransactionDataV1Volumebasedpricing403ErrorException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.",
                                (reason, context) -> new TransactionDataV1Volumebasedpricing404ErrorException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("The server encountered an unexpected condition that  prevented it from fulfilling the request.",
                                (reason, context) -> new TransactionDataV1Volumebasedpricing500ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This API returns the fee/charges levied from a customer's account in a billing period or date
     * range. The API returns both billed and unbilled fee items. To get the summary of charges, the
     * endpoint *transaction/feessummary* should be called with the same input criteria. ####
     * Supported operations * Get fees by invoice status * Get fees by date period * Get fees by
     * account * Get fees by card Id or PAN * Get fees by fee type charges * Get fees including
     * cancelled items * Get fees by line item description * Get fees by product.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: Transaction Fees RequestBody
     * @return    Returns the TransactionFeesRes response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public TransactionFeesRes fees(
            final String requestId,
            final TransactionFeesReq body) throws ApiException, IOException {
        return prepareFeesRequest(requestId, body).execute();
    }

    /**
     * This API returns the fee/charges levied from a customer's account in a billing period or date
     * range. The API returns both billed and unbilled fee items. To get the summary of charges, the
     * endpoint *transaction/feessummary* should be called with the same input criteria. ####
     * Supported operations * Get fees by invoice status * Get fees by date period * Get fees by
     * account * Get fees by card Id or PAN * Get fees by fee type charges * Get fees including
     * cancelled items * Get fees by line item description * Get fees by product.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: Transaction Fees RequestBody
     * @return    Returns the TransactionFeesRes response from the API call
     */
    public CompletableFuture<TransactionFeesRes> feesAsync(
            final String requestId,
            final TransactionFeesReq body) {
        try {
            return prepareFeesRequest(requestId, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for fees.
     */
    private ApiCall<TransactionFeesRes, ApiException> prepareFeesRequest(
            final String requestId,
            final TransactionFeesReq body) {
        return new ApiCall.Builder<TransactionFeesRes, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SHELL.value())
                        .path("/transaction-data/v1/fees")
                        .bodyParam(param -> param.value(body).isRequired(false))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("RequestId")
                                .value(requestId).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("BearerToken"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, TransactionFeesRes.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).",
                                (reason, context) -> new TransactionDataV1Fees400ErrorException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("The request has not been applied because it lacks valid  authentication credentials for the target resource.",
                                (reason, context) -> new TransactionDataV1Fees401ErrorException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new TransactionDataV1Fees403ErrorException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.",
                                (reason, context) -> new TransactionDataV1Fees404ErrorException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("The server encountered an unexpected condition that  prevented it from fulfilling the request.",
                                (reason, context) -> new TransactionDataV1Fees500ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This API returns the summary data of the fee/charges levied from a customer's account in a
     * billing period or date range. The API returns both billed and unbilled fee items. The
     * endpoint supports the exact same search criteria as the endpoint *transaction/feessummary*.
     * #### Supported operations * Get fees by invoice status * Get fees by date period * Get fees
     * by account * Get fees by card Id or PAN * Get fees by fee type charges * Get fees including
     * cancelled items * Get fees by line item description * Get fees by product.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: FeeSummary RequestBody
     * @return    Returns the FeeSummaryResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public FeeSummaryResponse feeSummaryResponse(
            final String requestId,
            final TransactionFeesSummaryReq body) throws ApiException, IOException {
        return prepareFeeSummaryResponseRequest(requestId, body).execute();
    }

    /**
     * This API returns the summary data of the fee/charges levied from a customer's account in a
     * billing period or date range. The API returns both billed and unbilled fee items. The
     * endpoint supports the exact same search criteria as the endpoint *transaction/feessummary*.
     * #### Supported operations * Get fees by invoice status * Get fees by date period * Get fees
     * by account * Get fees by card Id or PAN * Get fees by fee type charges * Get fees including
     * cancelled items * Get fees by line item description * Get fees by product.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: FeeSummary RequestBody
     * @return    Returns the FeeSummaryResponse response from the API call
     */
    public CompletableFuture<FeeSummaryResponse> feeSummaryResponseAsync(
            final String requestId,
            final TransactionFeesSummaryReq body) {
        try {
            return prepareFeeSummaryResponseRequest(requestId, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for feeSummaryResponse.
     */
    private ApiCall<FeeSummaryResponse, ApiException> prepareFeeSummaryResponseRequest(
            final String requestId,
            final TransactionFeesSummaryReq body) {
        return new ApiCall.Builder<FeeSummaryResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SHELL.value())
                        .path("/transaction-data/v1/feessummary")
                        .bodyParam(param -> param.value(body).isRequired(false))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("RequestId")
                                .value(requestId).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("BearerToken"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, FeeSummaryResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).",
                                (reason, context) -> new TransactionDataV1Feessummary400ErrorException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("The request has not been applied because it lacks valid  authentication credentials for the target resource.",
                                (reason, context) -> new TransactionDataV1Feessummary401ErrorException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new TransactionDataV1Feessummary403ErrorException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.",
                                (reason, context) -> new TransactionDataV1Feessummary404ErrorException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("The server encountered an unexpected condition that  prevented it from fulfilling the request.",
                                (reason, context) -> new TransactionDataV1Feessummary500ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * - This API returns the customer an overview of how many transactions, how much fuel volume
     * used over a given period and the total volume used by a card - This operation response will
     * contains card &amp; transaction details for given period aggregated by payer, account, cardGroup,
     * PAN, DriverName and VRN.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: FuelConsumption RequestBody
     * @return    Returns the FuelConsumptionResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public FuelConsumptionResponse fuelConsumption(
            final String requestId,
            final FuelConsumptionReq body) throws ApiException, IOException {
        return prepareFuelConsumptionRequest(requestId, body).execute();
    }

    /**
     * - This API returns the customer an overview of how many transactions, how much fuel volume
     * used over a given period and the total volume used by a card - This operation response will
     * contains card &amp; transaction details for given period aggregated by payer, account, cardGroup,
     * PAN, DriverName and VRN.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: FuelConsumption RequestBody
     * @return    Returns the FuelConsumptionResponse response from the API call
     */
    public CompletableFuture<FuelConsumptionResponse> fuelConsumptionAsync(
            final String requestId,
            final FuelConsumptionReq body) {
        try {
            return prepareFuelConsumptionRequest(requestId, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for fuelConsumption.
     */
    private ApiCall<FuelConsumptionResponse, ApiException> prepareFuelConsumptionRequest(
            final String requestId,
            final FuelConsumptionReq body) {
        return new ApiCall.Builder<FuelConsumptionResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SHELL.value())
                        .path("/transaction-data/v1/fuelconsumption")
                        .bodyParam(param -> param.value(body).isRequired(false))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("RequestId")
                                .value(requestId).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("BearerToken"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, FuelConsumptionResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).",
                                (reason, context) -> new TransactionDataV1Fuelconsumption400ErrorException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("The request has not been applied because it lacks valid  authentication credentials for the target resource.",
                                (reason, context) -> new TransactionDataV1Fuelconsumption401ErrorException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new TransactionDataV1Fuelconsumption403ErrorException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.",
                                (reason, context) -> new TransactionDataV1Fuelconsumption404ErrorException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("The server encountered an unexpected condition that  prevented it from fulfilling the request.",
                                (reason, context) -> new TransactionDataV1Fuelconsumption500ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * - This API allows the users to update the odometer readings on the sales items (transaction
     * data) - This is an asynchronous operation. If opted, the user will be notified on completion
     * of processing.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: updateOdometer RequestBody
     * @return    Returns the UpdateOdometerResp response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public UpdateOdometerResp updateOdometer(
            final String requestId,
            final UpdateOdometerRequest body) throws ApiException, IOException {
        return prepareUpdateOdometerRequest(requestId, body).execute();
    }

    /**
     * - This API allows the users to update the odometer readings on the sales items (transaction
     * data) - This is an asynchronous operation. If opted, the user will be notified on completion
     * of processing.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: updateOdometer RequestBody
     * @return    Returns the UpdateOdometerResp response from the API call
     */
    public CompletableFuture<UpdateOdometerResp> updateOdometerAsync(
            final String requestId,
            final UpdateOdometerRequest body) {
        try {
            return prepareUpdateOdometerRequest(requestId, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for updateOdometer.
     */
    private ApiCall<UpdateOdometerResp, ApiException> prepareUpdateOdometerRequest(
            final String requestId,
            final UpdateOdometerRequest body) {
        return new ApiCall.Builder<UpdateOdometerResp, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SHELL.value())
                        .path("/transaction-data/v1/updateodometer")
                        .bodyParam(param -> param.value(body).isRequired(false))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("RequestId")
                                .value(requestId).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("BearerToken"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, UpdateOdometerResp.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).",
                                (reason, context) -> new TransactionDataV1Updateodometer400ErrorException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("The request has not been applied because it lacks valid  authentication credentials for the target resource.",
                                (reason, context) -> new TransactionDataV1Updateodometer401ErrorException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new TransactionDataV1Updateodometer403ErrorException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.",
                                (reason, context) -> new TransactionDataV1Updateodometer404ErrorException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("The server encountered an unexpected condition that  prevented it from fulfilling the request.",
                                (reason, context) -> new TransactionDataV1Updateodometer500ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * - This API provides the details of the Cards or Transaction related exceptions based on the
     * given conditions for the Requested period. - This API will return the Transactions related
     * exceptions when the OutputType input parameter is passed as ‘Transaction’ else will return
     * the Cards related exceptions.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: Transaction Exceptions RequestBody
     * @return    Returns the TransactionExceptionsRes response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public TransactionExceptionsRes transactionExceptions(
            final String requestId,
            final TransactionExceptionsReq body) throws ApiException, IOException {
        return prepareTransactionExceptionsRequest(requestId, body).execute();
    }

    /**
     * - This API provides the details of the Cards or Transaction related exceptions based on the
     * given conditions for the Requested period. - This API will return the Transactions related
     * exceptions when the OutputType input parameter is passed as ‘Transaction’ else will return
     * the Cards related exceptions.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: Transaction Exceptions RequestBody
     * @return    Returns the TransactionExceptionsRes response from the API call
     */
    public CompletableFuture<TransactionExceptionsRes> transactionExceptionsAsync(
            final String requestId,
            final TransactionExceptionsReq body) {
        try {
            return prepareTransactionExceptionsRequest(requestId, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for transactionExceptions.
     */
    private ApiCall<TransactionExceptionsRes, ApiException> prepareTransactionExceptionsRequest(
            final String requestId,
            final TransactionExceptionsReq body) {
        return new ApiCall.Builder<TransactionExceptionsRes, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SHELL.value())
                        .path("/transaction-data/v1/exceptions")
                        .bodyParam(param -> param.value(body).isRequired(false))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("RequestId")
                                .value(requestId).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("BearerToken"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, TransactionExceptionsRes.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).",
                                (reason, context) -> new TransactionDataV1Exceptions400ErrorException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("The request has not been applied because it lacks valid  authentication credentials for the target resource.",
                                (reason, context) -> new TransactionDataV1Exceptions401ErrorException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new TransactionDataV1Exceptions403ErrorException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.",
                                (reason, context) -> new TransactionDataV1Exceptions404ErrorException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("The server encountered an unexpected condition that  prevented it from fulfilling the request.",
                                (reason, context) -> new TransactionDataV1Exceptions500ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint allows querying last 48 hours of transaction data of Shell Card (i.e. Priced,
     * Billed, Unbilled etc. sales items). It provides a flexible search criteria and supports
     * pagination. E.g., if the request is made at 08:30 AM on 18 Aug 2022 then transactions until
     * 16 Aug 2022 08:30 AM (including) can be retrieved. #### Supported operations * Search by Date
     * and Time range (within the last 48 hours only) * Search by Payer and/or Account number *
     * Search by Card * Search by Purchased Country * Search by Transaction posting date * Search by
     * Driver Name or Vehicle registration number * Search by Fuel only transactions * Search by
     * Product and/or Product group.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: New Recent Transaction RequestBody
     * @return    Returns the RecentTransactionsResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public RecentTransactionsResponse recentTransactionsNew(
            final String requestId,
            final RecentTransactionRequest body) throws ApiException, IOException {
        return prepareRecentTransactionsNewRequest(requestId, body).execute();
    }

    /**
     * This endpoint allows querying last 48 hours of transaction data of Shell Card (i.e. Priced,
     * Billed, Unbilled etc. sales items). It provides a flexible search criteria and supports
     * pagination. E.g., if the request is made at 08:30 AM on 18 Aug 2022 then transactions until
     * 16 Aug 2022 08:30 AM (including) can be retrieved. #### Supported operations * Search by Date
     * and Time range (within the last 48 hours only) * Search by Payer and/or Account number *
     * Search by Card * Search by Purchased Country * Search by Transaction posting date * Search by
     * Driver Name or Vehicle registration number * Search by Fuel only transactions * Search by
     * Product and/or Product group.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: New Recent Transaction RequestBody
     * @return    Returns the RecentTransactionsResponse response from the API call
     */
    public CompletableFuture<RecentTransactionsResponse> recentTransactionsNewAsync(
            final String requestId,
            final RecentTransactionRequest body) {
        try {
            return prepareRecentTransactionsNewRequest(requestId, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for recentTransactionsNew.
     */
    private ApiCall<RecentTransactionsResponse, ApiException> prepareRecentTransactionsNewRequest(
            final String requestId,
            final RecentTransactionRequest body) {
        return new ApiCall.Builder<RecentTransactionsResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SHELL.value())
                        .path("/transaction-data/v1/recent")
                        .bodyParam(param -> param.value(body).isRequired(false))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("RequestId")
                                .value(requestId).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("BearerToken"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, RecentTransactionsResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).",
                                (reason, context) -> new TransactionDataV1Recent400ErrorException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("The request has not been applied because it lacks valid  authentication credentials for the target resource.",
                                (reason, context) -> new TransactionDataV1Recent401ErrorException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new TransactionDataV1Recent403ErrorException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.",
                                (reason, context) -> new TransactionDataV1Recent404ErrorException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("The server encountered an unexpected condition that  prevented it from fulfilling the request.",
                                (reason, context) -> new TransactionDataV1Recent500ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This API allows querying transaction data (i.e. Priced, Billed and Unbilled sales items). It
     * provides a flexible search criteria and supports paging. The version 2 is an enhancement to
     * the version 1 where EV transactions and their details are added in the response. Transactions
     * that are posted but not yet priced, billed or that are in error will not be returned by this
     * API. The API also supports returning Fee Items. #### Supported operations * Get sales items
     * and fee transactions * Search by invoice status * Search by fixed date period * Search by
     * date range * Search by account * Search by card * Get sales items only * Search by
     * transaction Id or location * Search by transaction posting date * Search by invoice number or
     * date * Search by driver name or vehicle registration number * Search by card group * Search
     * by fuel only transactions * Search by product * EV transaction details - Below are EV
     * specific parameters * EVOperator * EVSerialId * EVChargePointSerial *
     * EVChargePointConnectorType * EVChargePointConnectorTypeDescription * EVChargeDuration *
     * EVChargeStartDate * EVChargeStartTime * EVChargeEndDate * EVChargeEndTime.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: Priced TransactionV2 RequestBody
     * @return    Returns the PricedTransactionResponseV2 response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public PricedTransactionResponseV2 pricedTransactionsV2(
            final String requestId,
            final PricedTransactionRequestV2 body) throws ApiException, IOException {
        return preparePricedTransactionsV2Request(requestId, body).execute();
    }

    /**
     * This API allows querying transaction data (i.e. Priced, Billed and Unbilled sales items). It
     * provides a flexible search criteria and supports paging. The version 2 is an enhancement to
     * the version 1 where EV transactions and their details are added in the response. Transactions
     * that are posted but not yet priced, billed or that are in error will not be returned by this
     * API. The API also supports returning Fee Items. #### Supported operations * Get sales items
     * and fee transactions * Search by invoice status * Search by fixed date period * Search by
     * date range * Search by account * Search by card * Get sales items only * Search by
     * transaction Id or location * Search by transaction posting date * Search by invoice number or
     * date * Search by driver name or vehicle registration number * Search by card group * Search
     * by fuel only transactions * Search by product * EV transaction details - Below are EV
     * specific parameters * EVOperator * EVSerialId * EVChargePointSerial *
     * EVChargePointConnectorType * EVChargePointConnectorTypeDescription * EVChargeDuration *
     * EVChargeStartDate * EVChargeStartTime * EVChargeEndDate * EVChargeEndTime.
     * @param  requestId  Required parameter: Mandatory UUID (according to RFC 4122 standards) for
     *         requests and responses. This will be played back in the response from the request.
     * @param  body  Optional parameter: Priced TransactionV2 RequestBody
     * @return    Returns the PricedTransactionResponseV2 response from the API call
     */
    public CompletableFuture<PricedTransactionResponseV2> pricedTransactionsV2Async(
            final String requestId,
            final PricedTransactionRequestV2 body) {
        try {
            return preparePricedTransactionsV2Request(requestId, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for pricedTransactionsV2.
     */
    private ApiCall<PricedTransactionResponseV2, ApiException> preparePricedTransactionsV2Request(
            final String requestId,
            final PricedTransactionRequestV2 body) {
        return new ApiCall.Builder<PricedTransactionResponseV2, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SHELL.value())
                        .path("/transaction-data/v1/priced")
                        .bodyParam(param -> param.value(body).isRequired(false))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("RequestId")
                                .value(requestId).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("BearerToken"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, PricedTransactionResponseV2.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).",
                                (reason, context) -> new TransactionDataV1Priced400ErrorException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("The request has not been applied because it lacks valid  authentication credentials for the target resource.",
                                (reason, context) -> new TransactionDataV1Priced401ErrorException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new TransactionDataV1Priced403ErrorException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.",
                                (reason, context) -> new TransactionDataV1Priced404ErrorException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("The server encountered an unexpected condition that  prevented it from fulfilling the request.",
                                (reason, context) -> new TransactionDataV1Priced500ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}