/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for AuditArrayElements type.
 */
public class AuditArrayElements {
    private List<AuditResponseAuditsItems> audits;

    /**
     * Default constructor.
     */
    public AuditArrayElements() {
    }

    /**
     * Initialization constructor.
     * @param  audits  List of AuditResponseAuditsItems value for audits.
     */
    public AuditArrayElements(
            List<AuditResponseAuditsItems> audits) {
        this.audits = audits;
    }

    /**
     * Getter for Audits.
     * @return Returns the List of AuditResponseAuditsItems
     */
    @JsonGetter("Audits")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<AuditResponseAuditsItems> getAudits() {
        return audits;
    }

    /**
     * Setter for Audits.
     * @param audits Value for List of AuditResponseAuditsItems
     */
    @JsonSetter("Audits")
    public void setAudits(List<AuditResponseAuditsItems> audits) {
        this.audits = audits;
    }

    /**
     * Converts this AuditArrayElements into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AuditArrayElements [" + "audits=" + audits + "]";
    }

    /**
     * Builds a new {@link AuditArrayElements.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AuditArrayElements.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .audits(getAudits());
        return builder;
    }

    /**
     * Class to build instances of {@link AuditArrayElements}.
     */
    public static class Builder {
        private List<AuditResponseAuditsItems> audits;



        /**
         * Setter for audits.
         * @param  audits  List of AuditResponseAuditsItems value for audits.
         * @return Builder
         */
        public Builder audits(List<AuditResponseAuditsItems> audits) {
            this.audits = audits;
            return this;
        }

        /**
         * Builds a new {@link AuditArrayElements} object using the set fields.
         * @return {@link AuditArrayElements}
         */
        public AuditArrayElements build() {
            return new AuditArrayElements(audits);
        }
    }
}
