/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;

/**
 * This is a model class for AuditReq type.
 */
public class AuditReq {
    private AuditRequest filters;
    private OptionalNullable<Integer> page;
    private OptionalNullable<Integer> pageSize;

    /**
     * Default constructor.
     */
    public AuditReq() {
        page = OptionalNullable.of(1);
        pageSize = OptionalNullable.of(50);
    }

    /**
     * Initialization constructor.
     * @param  filters  AuditRequest value for filters.
     * @param  page  Integer value for page.
     * @param  pageSize  Integer value for pageSize.
     */
    public AuditReq(
            AuditRequest filters,
            Integer page,
            Integer pageSize) {
        this.filters = filters;
        this.page = OptionalNullable.of(page);
        this.pageSize = OptionalNullable.of(pageSize);
    }

    /**
     * Initialization constructor.
     * @param  filters  AuditRequest value for filters.
     * @param  page  Integer value for page.
     * @param  pageSize  Integer value for pageSize.
     */

    protected AuditReq(AuditRequest filters, OptionalNullable<Integer> page,
            OptionalNullable<Integer> pageSize) {
        this.filters = filters;
        this.page = page;
        this.pageSize = pageSize;
    }

    /**
     * Getter for Filters.
     * @return Returns the AuditRequest
     */
    @JsonGetter("Filters")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AuditRequest getFilters() {
        return filters;
    }

    /**
     * Setter for Filters.
     * @param filters Value for AuditRequest
     */
    @JsonSetter("Filters")
    public void setFilters(AuditRequest filters) {
        this.filters = filters;
    }

    /**
     * Internal Getter for Page.
     * Page Number (as shown to the users)
     * @return Returns the Internal Integer
     */
    @JsonGetter("Page")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetPage() {
        return this.page;
    }

    /**
     * Getter for Page.
     * Page Number (as shown to the users)
     * @return Returns the Integer
     */
    public Integer getPage() {
        return OptionalNullable.getFrom(page);
    }

    /**
     * Setter for Page.
     * Page Number (as shown to the users)
     * @param page Value for Integer
     */
    @JsonSetter("Page")
    public void setPage(Integer page) {
        this.page = OptionalNullable.of(page);
    }

    /**
     * UnSetter for Page.
     * Page Number (as shown to the users)
     */
    public void unsetPage() {
        page = null;
    }

    /**
     * Internal Getter for PageSize.
     * Page Size – Number of records to show on a page.
     * @return Returns the Internal Integer
     */
    @JsonGetter("PageSize")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetPageSize() {
        return this.pageSize;
    }

    /**
     * Getter for PageSize.
     * Page Size – Number of records to show on a page.
     * @return Returns the Integer
     */
    public Integer getPageSize() {
        return OptionalNullable.getFrom(pageSize);
    }

    /**
     * Setter for PageSize.
     * Page Size – Number of records to show on a page.
     * @param pageSize Value for Integer
     */
    @JsonSetter("PageSize")
    public void setPageSize(Integer pageSize) {
        this.pageSize = OptionalNullable.of(pageSize);
    }

    /**
     * UnSetter for PageSize.
     * Page Size – Number of records to show on a page.
     */
    public void unsetPageSize() {
        pageSize = null;
    }

    /**
     * Converts this AuditReq into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AuditReq [" + "filters=" + filters + ", page=" + page + ", pageSize=" + pageSize
                + "]";
    }

    /**
     * Builds a new {@link AuditReq.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AuditReq.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .filters(getFilters());
        builder.page = internalGetPage();
        builder.pageSize = internalGetPageSize();
        return builder;
    }

    /**
     * Class to build instances of {@link AuditReq}.
     */
    public static class Builder {
        private AuditRequest filters;
        private OptionalNullable<Integer> page = OptionalNullable.of(1);
        private OptionalNullable<Integer> pageSize = OptionalNullable.of(50);



        /**
         * Setter for filters.
         * @param  filters  AuditRequest value for filters.
         * @return Builder
         */
        public Builder filters(AuditRequest filters) {
            this.filters = filters;
            return this;
        }

        /**
         * Setter for page.
         * @param  page  Integer value for page.
         * @return Builder
         */
        public Builder page(Integer page) {
            this.page = OptionalNullable.of(page);
            return this;
        }

        /**
         * UnSetter for page.
         * @return Builder
         */
        public Builder unsetPage() {
            page = null;
            return this;
        }

        /**
         * Setter for pageSize.
         * @param  pageSize  Integer value for pageSize.
         * @return Builder
         */
        public Builder pageSize(Integer pageSize) {
            this.pageSize = OptionalNullable.of(pageSize);
            return this;
        }

        /**
         * UnSetter for pageSize.
         * @return Builder
         */
        public Builder unsetPageSize() {
            pageSize = null;
            return this;
        }

        /**
         * Builds a new {@link AuditReq} object using the set fields.
         * @return {@link AuditReq}
         */
        public AuditReq build() {
            return new AuditReq(filters, page, pageSize);
        }
    }
}
