/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for CardUsageSummaryRes type.
 */
public class CardUsageSummaryRes {
    private String requestId;
    private String status;
    private List<CardUsageSummaryResponse> data;
    private List<Warning> warnings;

    /**
     * Default constructor.
     */
    public CardUsageSummaryRes() {
    }

    /**
     * Initialization constructor.
     * @param  requestId  String value for requestId.
     * @param  status  String value for status.
     * @param  data  List of CardUsageSummaryResponse value for data.
     * @param  warnings  List of Warning value for warnings.
     */
    public CardUsageSummaryRes(
            String requestId,
            String status,
            List<CardUsageSummaryResponse> data,
            List<Warning> warnings) {
        this.requestId = requestId;
        this.status = status;
        this.data = data;
        this.warnings = warnings;
    }

    /**
     * Getter for RequestId.
     * Unique identifier for the request. This will be played back in the response from the request.
     * @return Returns the String
     */
    @JsonGetter("RequestId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRequestId() {
        return requestId;
    }

    /**
     * Setter for RequestId.
     * Unique identifier for the request. This will be played back in the response from the request.
     * @param requestId Value for String
     */
    @JsonSetter("RequestId")
    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    /**
     * Getter for Status.
     * Status of the request
     * @return Returns the String
     */
    @JsonGetter("Status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Status of the request
     * @param status Value for String
     */
    @JsonSetter("Status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for Data.
     * @return Returns the List of CardUsageSummaryResponse
     */
    @JsonGetter("Data")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<CardUsageSummaryResponse> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for List of CardUsageSummaryResponse
     */
    @JsonSetter("Data")
    public void setData(List<CardUsageSummaryResponse> data) {
        this.data = data;
    }

    /**
     * Getter for Warnings.
     * A list of Warning entity. This entity will hold the details of the scheduled System Outages
     * of any dependent applications of this service. Note: If there is no scheduled outage
     * information available, in the configuration in AMS, for this service, this parameter won’t be
     * present in output.
     * @return Returns the List of Warning
     */
    @JsonGetter("Warnings")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Warning> getWarnings() {
        return warnings;
    }

    /**
     * Setter for Warnings.
     * A list of Warning entity. This entity will hold the details of the scheduled System Outages
     * of any dependent applications of this service. Note: If there is no scheduled outage
     * information available, in the configuration in AMS, for this service, this parameter won’t be
     * present in output.
     * @param warnings Value for List of Warning
     */
    @JsonSetter("Warnings")
    public void setWarnings(List<Warning> warnings) {
        this.warnings = warnings;
    }

    /**
     * Converts this CardUsageSummaryRes into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CardUsageSummaryRes [" + "requestId=" + requestId + ", status=" + status + ", data="
                + data + ", warnings=" + warnings + "]";
    }

    /**
     * Builds a new {@link CardUsageSummaryRes.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CardUsageSummaryRes.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .requestId(getRequestId())
                .status(getStatus())
                .data(getData())
                .warnings(getWarnings());
        return builder;
    }

    /**
     * Class to build instances of {@link CardUsageSummaryRes}.
     */
    public static class Builder {
        private String requestId;
        private String status;
        private List<CardUsageSummaryResponse> data;
        private List<Warning> warnings;



        /**
         * Setter for requestId.
         * @param  requestId  String value for requestId.
         * @return Builder
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for data.
         * @param  data  List of CardUsageSummaryResponse value for data.
         * @return Builder
         */
        public Builder data(List<CardUsageSummaryResponse> data) {
            this.data = data;
            return this;
        }

        /**
         * Setter for warnings.
         * @param  warnings  List of Warning value for warnings.
         * @return Builder
         */
        public Builder warnings(List<Warning> warnings) {
            this.warnings = warnings;
            return this;
        }

        /**
         * Builds a new {@link CardUsageSummaryRes} object using the set fields.
         * @return {@link CardUsageSummaryRes}
         */
        public CardUsageSummaryRes build() {
            return new CardUsageSummaryRes(requestId, status, data, warnings);
        }
    }
}
