/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for ErrorObject type.
 */
public class ErrorObject {
    private String requestId;
    private String status;
    private List<ErrorDetails> errors;

    /**
     * Default constructor.
     */
    public ErrorObject() {
    }

    /**
     * Initialization constructor.
     * @param  requestId  String value for requestId.
     * @param  status  String value for status.
     * @param  errors  List of ErrorDetails value for errors.
     */
    public ErrorObject(
            String requestId,
            String status,
            List<ErrorDetails> errors) {
        this.requestId = requestId;
        this.status = status;
        this.errors = errors;
    }

    /**
     * Getter for RequestId.
     * Unique request identifier passed from end user. This identifier helps in tracing a
     * transaction
     * @return Returns the String
     */
    @JsonGetter("RequestId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRequestId() {
        return requestId;
    }

    /**
     * Setter for RequestId.
     * Unique request identifier passed from end user. This identifier helps in tracing a
     * transaction
     * @param requestId Value for String
     */
    @JsonSetter("RequestId")
    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    /**
     * Getter for Status.
     * Indicates overall status of the request. Allowed values: SUCCES, FAILED, PARTIAL_SUCCESS
     * @return Returns the String
     */
    @JsonGetter("Status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Indicates overall status of the request. Allowed values: SUCCES, FAILED, PARTIAL_SUCCESS
     * @param status Value for String
     */
    @JsonSetter("Status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for Errors.
     * @return Returns the List of ErrorDetails
     */
    @JsonGetter("Errors")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<ErrorDetails> getErrors() {
        return errors;
    }

    /**
     * Setter for Errors.
     * @param errors Value for List of ErrorDetails
     */
    @JsonSetter("Errors")
    public void setErrors(List<ErrorDetails> errors) {
        this.errors = errors;
    }

    /**
     * Converts this ErrorObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ErrorObject [" + "requestId=" + requestId + ", status=" + status + ", errors="
                + errors + "]";
    }

    /**
     * Builds a new {@link ErrorObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ErrorObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .requestId(getRequestId())
                .status(getStatus())
                .errors(getErrors());
        return builder;
    }

    /**
     * Class to build instances of {@link ErrorObject}.
     */
    public static class Builder {
        private String requestId;
        private String status;
        private List<ErrorDetails> errors;



        /**
         * Setter for requestId.
         * @param  requestId  String value for requestId.
         * @return Builder
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for errors.
         * @param  errors  List of ErrorDetails value for errors.
         * @return Builder
         */
        public Builder errors(List<ErrorDetails> errors) {
            this.errors = errors;
            return this;
        }

        /**
         * Builds a new {@link ErrorObject} object using the set fields.
         * @return {@link ErrorObject}
         */
        public ErrorObject build() {
            return new ErrorObject(requestId, status, errors);
        }
    }
}
