/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for UpdateOdometerResponse type.
 */
public class UpdateOdometerResponse {
    private Integer serviceReference;
    private List<UpdateOdometerReference> updateOdometerReferences;
    private ErrorStatus error;
    private String requestId;

    /**
     * Default constructor.
     */
    public UpdateOdometerResponse() {
    }

    /**
     * Initialization constructor.
     * @param  serviceReference  Integer value for serviceReference.
     * @param  updateOdometerReferences  List of UpdateOdometerReference value for
     *         updateOdometerReferences.
     * @param  error  ErrorStatus value for error.
     * @param  requestId  String value for requestId.
     */
    public UpdateOdometerResponse(
            Integer serviceReference,
            List<UpdateOdometerReference> updateOdometerReferences,
            ErrorStatus error,
            String requestId) {
        this.serviceReference = serviceReference;
        this.updateOdometerReferences = updateOdometerReferences;
        this.error = error;
        this.requestId = requestId;
    }

    /**
     * Getter for ServiceReference.
     * Main reference number for tracking.
     * @return Returns the Integer
     */
    @JsonGetter("ServiceReference")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getServiceReference() {
        return serviceReference;
    }

    /**
     * Setter for ServiceReference.
     * Main reference number for tracking.
     * @param serviceReference Value for Integer
     */
    @JsonSetter("ServiceReference")
    public void setServiceReference(Integer serviceReference) {
        this.serviceReference = serviceReference;
    }

    /**
     * Getter for UpdateOdometerReferences.
     * @return Returns the List of UpdateOdometerReference
     */
    @JsonGetter("UpdateOdometerReferences")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<UpdateOdometerReference> getUpdateOdometerReferences() {
        return updateOdometerReferences;
    }

    /**
     * Setter for UpdateOdometerReferences.
     * @param updateOdometerReferences Value for List of UpdateOdometerReference
     */
    @JsonSetter("UpdateOdometerReferences")
    public void setUpdateOdometerReferences(List<UpdateOdometerReference> updateOdometerReferences) {
        this.updateOdometerReferences = updateOdometerReferences;
    }

    /**
     * Getter for Error.
     * @return Returns the ErrorStatus
     */
    @JsonGetter("Error")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ErrorStatus getError() {
        return error;
    }

    /**
     * Setter for Error.
     * @param error Value for ErrorStatus
     */
    @JsonSetter("Error")
    public void setError(ErrorStatus error) {
        this.error = error;
    }

    /**
     * Getter for RequestId.
     * API Request Id
     * @return Returns the String
     */
    @JsonGetter("RequestId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRequestId() {
        return requestId;
    }

    /**
     * Setter for RequestId.
     * API Request Id
     * @param requestId Value for String
     */
    @JsonSetter("RequestId")
    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    /**
     * Converts this UpdateOdometerResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UpdateOdometerResponse [" + "serviceReference=" + serviceReference
                + ", updateOdometerReferences=" + updateOdometerReferences + ", error=" + error
                + ", requestId=" + requestId + "]";
    }

    /**
     * Builds a new {@link UpdateOdometerResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UpdateOdometerResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .serviceReference(getServiceReference())
                .updateOdometerReferences(getUpdateOdometerReferences())
                .error(getError())
                .requestId(getRequestId());
        return builder;
    }

    /**
     * Class to build instances of {@link UpdateOdometerResponse}.
     */
    public static class Builder {
        private Integer serviceReference;
        private List<UpdateOdometerReference> updateOdometerReferences;
        private ErrorStatus error;
        private String requestId;



        /**
         * Setter for serviceReference.
         * @param  serviceReference  Integer value for serviceReference.
         * @return Builder
         */
        public Builder serviceReference(Integer serviceReference) {
            this.serviceReference = serviceReference;
            return this;
        }

        /**
         * Setter for updateOdometerReferences.
         * @param  updateOdometerReferences  List of UpdateOdometerReference value for
         *         updateOdometerReferences.
         * @return Builder
         */
        public Builder updateOdometerReferences(
                List<UpdateOdometerReference> updateOdometerReferences) {
            this.updateOdometerReferences = updateOdometerReferences;
            return this;
        }

        /**
         * Setter for error.
         * @param  error  ErrorStatus value for error.
         * @return Builder
         */
        public Builder error(ErrorStatus error) {
            this.error = error;
            return this;
        }

        /**
         * Setter for requestId.
         * @param  requestId  String value for requestId.
         * @return Builder
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * Builds a new {@link UpdateOdometerResponse} object using the set fields.
         * @return {@link UpdateOdometerResponse}
         */
        public UpdateOdometerResponse build() {
            return new UpdateOdometerResponse(serviceReference, updateOdometerReferences, error,
                    requestId);
        }
    }
}
